name: CI

on: [push]

jobs:
  build:
   runs-on: ubuntu-18.04

    name: Build
    strategy:
      matrix:
        node_version: [16, 18]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: run CI
        run: npm install 
      - name: run linter
				run: npm run lint 
			- name: run tests
        run: npm run test 
      - name: run build
				run: npm run build 

